### ISSUE TITLE
Retire nodejs-native recipe

### ISSUE THREAD

**Issue by priv-kweihmann** [priv-kweihmann/meta-sca#7675]
The current nodejs-native version provided by this layer is pretty much outdated and stopped working with python 3.10.

```
|   File "/opt/build/build/tmp/work/x86_64-linux/nodejs-native/12.22.7-r0/node-v12.22.7/deps/v8/third_party/jinja2/__init__.py", line 33, in <module>
|     from jinja2.environment import Environment, Template
|   File "/opt/build/build/tmp/work/x86_64-linux/nodejs-native/12.22.7-r0/node-v12.22.7/deps/v8/third_party/jinja2/environment.py", line 16, in <module>
|     from jinja2.defaults import BLOCK_START_STRING, \
|   File "/opt/build/build/tmp/work/x86_64-linux/nodejs-native/12.22.7-r0/node-v12.22.7/deps/v8/third_party/jinja2/defaults.py", line 32, in <module>
|     from jinja2.tests import TESTS as DEFAULT_TESTS
|   File "/opt/build/build/tmp/work/x86_64-linux/nodejs-native/12.22.7-r0/node-v12.22.7/deps/v8/third_party/jinja2/tests.py", line 13, in <module>
|     from collections import Mapping
| ImportError: cannot import name 'Mapping' from 'collections' (/opt/build/build/tmp/work/x86_64-linux/nodejs-native/12.22.7-r0/recipe-sysroot-native/usr/lib/python3.10/collections/__init__.py)
```

as nodejs ships their own copy of Jinja2.
A well maintained nodejs recipe is shipped with meta-oe, so we are going 

- to retire the recipe provided here
- force the requirement of having meta-oe in the layer setup for all npm based tools
